name: Test

on:
  push:
    branches-ignore:
      - renovate/**
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - "~1.25"
          - "~1.26"

    steps:
      - uses: actions/checkout@v7

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "${{ matrix.go_version }}"
          cache: true

      - run: go test -trimpath -coverpkg=./... -covermode=atomic -coverprofile=coverage.out -count=1 ./...

      - uses: codecov/codecov-action@v7
        with:
          files: coverage.out
